fix(client): Add Keep selected server on refresh
jespertheend/splix pull request #137
Opened 2023-12-01 16:37 UTC by abhishek-exists

fixes #96 

Let me know if I've missed any edge cases here.

2023-12-01 18:25 UTC, splixcord reviewed
If the lastSelectedEndpoint is no longer in the list after refreshing it selects the first item instead of recommended

2023-12-01 19:38 UTC, abhishek-exists commented
Nice catch, I've updated the logic.

2023-12-01 21:52 UTC, jespertheend commented on client/src/network/serverSelection.js
> +			(!lastSelectedEndpoint && server.recommended && !serverEndpoints.has(server.endpoint))
I think the logic can be simplified a bit, also `serverEndpoints.has(server.endpoint)` will always be true like this.
I think this should work:
```js
if (lastSelectedEndpoint && serverEndpoints.has(lastSelectedEndpoint)) {
	if (lastSelectedEndpoint == server.endPoint) {
		selectedEndpoint = optionEl;
	}
} else if (server.recommended) {
	selectedEndpoint = optionEl;
}
```

2023-12-01 22:18 UTC, splixcord commented on client/src/network/serverSelection.js
> +			(!lastSelectedEndpoint && server.recommended && !serverEndpoints.has(server.endpoint))
```js
server.recommended && (!lastSelectedEndpoint || !serverEndpoints.has(lastSelectedEndpoint)) ||
server.endpoint === lastSelectedEndpoint

2023-12-01 22:25 UTC, splixcord commented on client/src/network/serverSelection.js
> +			(!lastSelectedEndpoint && server.recommended && !serverEndpoints.has(server.endpoint))
I think after the loop can do `if (serverEndpoints.has(lastSelectedEndpoint)) selectedEndpoint = lastSelectedEndpoint;`

2023-12-02 12:30 UTC, jespertheend commented on client/src/network/serverSelection.js
> +			(!lastSelectedEndpoint && server.recommended && !serverEndpoints.has(server.endpoint))
Ah yeah good point. I think that would be even better.

2023-12-02 16:33 UTC, abhishek-exists commented on client/src/network/serverSelection.js
> +			(!lastSelectedEndpoint && server.recommended && !serverEndpoints.has(server.endpoint))
The only problem I see with the aforementioned method is that we have to go through the list again. As `selectedEndpoint` contains option-Element not the Endpoint. 
Otherwise, the `optionElement` needs to be kept in localStorage. Will that be okay?

2023-12-02 16:48 UTC, splixcord commented on client/src/network/serverSelection.js
> +			(!lastSelectedEndpoint && server.recommended && !serverEndpoints.has(server.endpoint))
Oh yeah my bad

2023-12-03 13:57 UTC, jespertheend commented on client/src/network/serverSelection.js
> +			(!lastSelectedEndpoint && server.recommended && !serverEndpoints.has(server.endpoint))
Ah yeah, you're right. Let's keep it like this then!

2023-12-03 14:00 UTC, jespertheend requested changes

2023-12-03 14:00 UTC, jespertheend commented on client/src/network/serverSelection.js
> +			if (lastSelectedEndpoint === server.endPoint) {
Sorry, seems like my suggestion had a mistake. It should be `endpoint` instead of `endPoint`

2023-12-04 03:21 UTC, abhishek-exists commented on client/src/network/serverSelection.js
> +			if (lastSelectedEndpoint === server.endPoint) {
My bad; I should have tested again. I included the changes in the most recent commit.

2023-12-04 10:36 UTC, jespertheend approved these changes
Thanks, LGTM!

2023-12-04 21:24 UTC, merged