fix(gs): Player loop fixes
jespertheend/splix pull request #57
Opened 2023-09-28 15:32 UTC by splixcord

Moved around some parts of the player loop to make it closer to the original server behaviour and is required for some further fixes
Moving only one tile per loop fixes an out of bounds tile crash
Fixes disconnected players not being removed for other players if they were paused

2023-09-30 14:46 UTC, jespertheend requested changes
Thanks! I had a couple of questions, but other than that this looks good!

2023-09-30 14:46 UTC, jespertheend commented on gameServer/src/gameplay/Player.js
> +				this.sendPlayerStateToPlayer(this);
This message was only sent when the last move was invalid in case the player happened to make a valid move again right after it. So basically let's say three moves get queued: A, B and C where only move B is invalid. In that case the player might get teleported back to wherever they were when they made move B, even though they have already made move C and should really be at that location.

I can't seem to find a scenario where this is the case right now, so this might not be a huge issue. But what exactly gets fixed with this change?

2023-09-30 14:46 UTC, jespertheend commented on gameServer/src/gameplay/Player.js
> -			this.#updateCurrentTile();
Isn't there a chance that the player might have moved back a few tiles and thus have changed the tile type they are currently on? `updateCurrentTile()` expects to be called whenever the current tile is changed, so I worry this might cause issues later on.

2023-09-30 14:46 UTC, jespertheend commented on gameServer/src/gameplay/Player.js
> +			if (this.#nextTileProgress > 1) {
Do you know how to reproduce the out of bounds tile crash?
The while loop makes sure moves are processed as fast as possible in case the server has a hiccup.
I think another fix might be more robust, most likely some state is not being updated correctly inside this while loop.

2023-09-30 14:46 UTC, jespertheend commented on gameServer/src/gameplay/Player.js
> -		if (this.#currentTileType != tileValue) {
Just curious, is there something that gets fixed by the removal of this if statement? I think it was only there for performance reasons because I expected the `updateCurrentTile` to be doing a lot of work, but it only has two checks in there so I reckon it likely doesn't make much of a difference performance wise.

`this.#currentTileType` is currently unused though, so you can remove that as well.

2023-09-30 14:46 UTC, jespertheend commented on gameServer/src/gameplay/Player.js
> +				this.#checkKills();
I think `checkKills()` can be moved to be called from inside `currentPositionChanged()`, since changing the position of a player should always immediately kill other players.
`currentPositionChanged()` is also called inside `drainMovementQueue()` and I wonder if, without the kills check, it's possible to jump over other trails without killing them.

2023-09-30 14:48 UTC, jespertheend commented
Oh by the way, where does #43 get fixed exactly? I thought it was fixed in #41 already but it seems like the server is still logging this stack trace at the moment.

2023-09-30 16:26 UTC, splixcord commented on gameServer/src/gameplay/Player.js
> +				this.sendPlayerStateToPlayer(this);
This makes it like the original server so that every move gets responded to in order, even invalid ones
![image](https://github.com/jespertheend/splix/assets/140275796/f62ca6fb-fc8b-4f54-ab2c-f0cabdf4ccbd)

2023-09-30 16:32 UTC, splixcord commented on gameServer/src/gameplay/Player.js
> -			this.#updateCurrentTile();
This is like the original server where tile type and collisions aren't checked when draining a move, allowing to undo onto a block that recently changed and not start a new trail, or undo onto a player and move again without killing them

2023-09-30 16:37 UTC, splixcord commented on gameServer/src/gameplay/Player.js
> +			if (this.#nextTileProgress > 1) {
The crash can be reproduced by freezing the server when pausing the debugger, and unpausing when the player should have move past the wall

The nextTileProgress decreases by 1 instead of resetting to 0 which lets the server catch up fast, processing one tile per loop makes sure that 2 players going towards each other from perpendicular directions won't skip a collision

2023-09-30 16:45 UTC, splixcord commented on gameServer/src/gameplay/Player.js
> -		if (this.#currentTileType != tileValue) {
This fixes flying without a trail, there are currently 2 ways and the removal of updateCurrentTile() inside drainMovementQueue() would add another

2023-09-30 16:49 UTC, splixcord commented on gameServer/src/gameplay/Player.js
> +				this.#checkKills();
I tried to make it as close to the original server as possible, where you can undo to go on a player as well as not killing a player that's in the block you spawn on

2023-09-30 17:01 UTC, splixcord commented
> Oh by the way, where does #43 get fixed exactly? I thought it was fixed in #41 already but it seems like the server is still logging this stack trace at the moment.

In checkNextMoveValidity it allowed positions positions ahead of you in lastUnpausedDirection if you were paused, and isFuturePosition is false for pause, which lets you teleport forward and skip things

2023-10-03 15:22 UTC, jespertheend commented on gameServer/src/gameplay/Player.js
> -			this.#updateCurrentTile();
I'm sorry but I'm not a big fan of deliberately introducing bugs that weren't there before, at least not yet. Maybe in the future this could go behind a flag or configuration of sorts. But more likely this will be something for custom servers hosted by the community.

2023-10-03 15:23 UTC, jespertheend commented on gameServer/src/gameplay/Player.js
> +				this.sendPlayerStateToPlayer(this);
Is there a specific scenario that benefits from this, or is the end result the same?

2023-10-03 15:25 UTC, jespertheend commented on gameServer/src/gameplay/Player.js
> +			if (this.#nextTileProgress > 1) {
Ah I see, not sure why the pausing the debugger triggers a crash, but two players missing each other is definitely a concern. I think the `if` statement will do for now, but in the future we'll probably want to call the `Player.loop()` from within the `Game.loop()` until all players have moved their entire distance.

2023-10-03 15:34 UTC, jespertheend commented on gameServer/src/gameplay/Player.js
> -		if (this.#currentTileType != tileValue) {
Ah that makes sense, but without the removal of `updateCurrentTile()` I don't think this change has much of an effect. You can leave this as is, or you can revert the change if you like. But if you decide to leave it as is, make sure to also remove the `#currentTileType` private variable as it is no longer used anywhere.

2023-10-03 15:37 UTC, jespertheend commented on gameServer/src/gameplay/Player.js
> +				this.#checkKills();
Ah, in that case that sounds like exactly the thing I was trying to avoid. Similarly, I think this would be better suited for a custom server or feature flag.

2023-10-03 15:39 UTC, jespertheend commented
> In checkNextMoveValidity it allowed positions ahead of you in lastUnpausedDirection if you were paused, and isFuturePosition is false for pause, which lets you teleport forward and skip things to cause various bugs

Ah I see, that makes sense. Thanks for the clarification!

2023-10-04 16:37 UTC, splixcord commented on gameServer/src/gameplay/Player.js
> +				this.sendPlayerStateToPlayer(this);
Reverted

2023-10-04 16:37 UTC, splixcord commented on gameServer/src/gameplay/Player.js
> -			this.#updateCurrentTile();
Reverted

2023-10-04 16:37 UTC, splixcord commented on gameServer/src/gameplay/Player.js
> -		if (this.#currentTileType != tileValue) {
Reverted

2023-10-04 16:37 UTC, splixcord commented on gameServer/src/gameplay/Player.js
> +				this.#checkKills();
Reverted

2023-10-07 21:31 UTC, jespertheend approved these changes
LGTM, thanks!

2023-10-09 19:01 UTC, merged